name: PHP Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'   # Change if your project needs another version

      - name: Verify PHP Version
        run: php -v

      - name: List project files
        run: ls -al
